### ISSUE TITLE
Not working on Unity 2022.3.62f3 right after import

### ISSUE THREAD

**Issue by snowly-handed** [Uralstech/UXR.QuestCamera#10]
Import package via UPM  + https://github.com/RageAgainstThePixel/com.utilities.async/ (I have newest 3.0.2 version)
See various errors, e.g.
Library\PackageCache\com.uralstech.uxr.questcamera@3.1.1\Runtime\Scripts\CaptureSession\SurfaceTextureCapture\OnDemandSurfaceTextureCaptureSession.cs(94,108): error CS0103: The name 'WaitTimeoutMode' does not exist in the current context

Did I miss something? on 6.0 unity it works fine. It looks like there are a few things missing in the com.utilities or there are differences between this and unity solution.

**Development environment:**
 - Unity version: [e.g. 2022.3]
 - Build target: [e.g. Android, Editor]
 - Package version: 3.1.1 / com.utilities.async 3.0.2

**Comment by Uralstech** [comment]
@snowly-handed, please try downloading the package from the [unstable](https://github.com/Uralstech/UXR.QuestCamera/tree/unstable) branch. I've added `UNITY_6000_0_OR_NEWER` guards to the methods using `WaitTimeoutMode` in d3be879. Thank you once again for reporting the issue!

**Comment by Uralstech** [comment]
I've published [UXR.QuestCamera v3.1.2](https://github.com/Uralstech/UXR.QuestCamera/releases/tag/3.1.2) with the fixes!
